version: "3.7"

services:
  http:
    container_name: testapp-http
    volumes:
      - ${PWD}/public:/var/www/html/public

  php-fpm:
    container_name: testapp-php
    volumes:
      - ${PWD}:/var/www/html