version: "3.7"

services:
  http:
    build:
      context: .
      dockerfile: Dockerfile.nginx

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
      target: php${PHP_VERSION}